spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MYSQL

  cloud:
    stream:
      default-binder: rabbit
      function:
        definition: execute-consumer
      bindings:
        # producers
        execute-producer-out-0:
          destination: queue

        # consumer
        execute-consumer-in-0:
          destination: queue

      rabbit:
        binder:
          brokers: localhost:5672

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

app:
  security:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000

---

spring:
  profiles: test
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
